name: Pipeline CI/CD Node.js

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Descargar código
      uses: actions/checkout@v4

    - name: 🟢 Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: 📦 Instalar dependencias
      run: npm install

    - name: 🚀 Ejecutar aplicación
      run: npm start

    - name: 🧪 Ejecutar tests
      run: npm test

    - name: 📅 Mostrar fecha
      run: date
